@include('home.header')
 <!-- Header Start -->
 <div class="container-fluid header bg-dark p-0">
  <div class="row g-0 align-items-center flex-column-reverse flex-md-row">
      <div class="col-md-6 p-5 mt-lg-5">
          <h1 class="display-5 animated fadeIn mb-4 text-primary">Refund Policy</h1> 
              <nav aria-label="breadcrumb animated fadeIn">
              <ol class="breadcrumb text-uppercase">
                  <li class="breadcrumb-item"><a href="{{ url('/terms-of-service') }}">Terms of service</a></li>
                  <li class="breadcrumb-item text-body active" aria-current="page">Refund policy</li>
              </ol>
          </nav>
      </div>
      <div class="col-md-6 animated fadeIn">
          <img class="img-fluid" src="img/mdterms.jpg" alt="">
      </div>
  </div>
</div>
<!-- Header End -->

<div class="container bg-white my-5">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <section>
        <p>At Media Deal, we strive to provide a transparent and satisfactory experience for all our users. Our refund policy is designed to address any issues related to ad placements and ensure fairness for both advertisers and media organizations.</p>

        <h5>Eligibility for Refunds</h5>
        <h6>1.	Non-Airings:</h6>
        <ul>If the ad aired does not match the agreed-upon content or schedule, and all attempts to air the agreed-upon content fail by the end of the campaign date, advertisers can request a refund.
          <li>Advertisers are eligible for a refund if the ad is not aired as per the agreed schedule, and all attempts to make-good fail by the end of the campaign date.</li>
        </ul>

        <h6>2.	Incorrect Airings:</h6>
        <ul>
          <li>If the ad aired does not match the agreed-upon content or schedule, and all attempts to air the agreed-upon content fail by the end of the campaign date, advertisers can request a refund.</li>
        </ul>

        <h6>3.	Technical Issues:</h6>
        <ul>
          <li>Refunds may be issued for technical issues that result in the ad failing, and all attempts to make-good fail, and the campaign date has elapsed.</li>
        </ul>

        <h6>4.	Ad Compliance Failures:</h6>
        <ul>
          <li>Refunds can be requested if the media organization fails to provide proof of ad airing or other required compliance documentation.</li>
        </ul>
      </section>

      <section>
        <h5>Refund Request Process</h5>
        <h6>1.	Submission:</h6>
        <ul>
          <li>Advertisers must submit a refund request through their Media Deal account within 3 days of the scheduled ad airing date..</li>
        </ul>

        <h6>2.	Documentation:</h6>
        <ul>
          <li>The request must include relevant documentation, such as proof of payment through the Media Deal platform, electronic receipt generated by Media Deal, and details of the issue.</li>
        </ul>

        <h6>3.	Review:</h6>
        <ul>
          <li>Media organizations will be notified of the refund request, and they are expected to review and respond to the request within 72 hours. </li>
        </ul>

        <h6>4.	Approval:</h6>
        <ul>
          <li>If the refund request is approved by the Media Organization, Media Deal will process the refund within 3 business days.</li>
        </ul>
      </section>

      <section>
        <h5>Media Deal Intervention</h5>
        <ul>
          <li>If a media organization fails to satisfactorily respond to a refund request, Media Deal will intervene.</li>
          <li>Media Deal reserves the right to suspend or deactivate media organizations that refuse to attend to refund requests.</li>
        </ul>
      </section>

      <section>
        <h5>Refund Amount</h5>
        <h6>1.	Transaction Fee:</h6>
        <ul>
          <li>All transactions on Media Deal incur a 5% deduction to cover system maintenance and payment processing. This fee is non-refundable.</li>
        </ul>

        <h6>2.	Partial Refunds:</h6>
        <ul>
          <li>In cases where the ad was partially aired or partially incorrect, a partial refund may be issued based on the extent of the issue.</li>
        </ul>
      </section>

      <section>
        <h5>Exceptions</h5>
        <h6>1.	Force Majeure:</h6>
        <ul>
          <li>Refunds are not issued for failures to air due to unforeseen circumstances such as natural disasters, technical failures outside the control of the media organization, or other force majeure events.</li>
        </ul>

        <h6>2.	Advertiser Errors:</h6>
        <ul>
          <li>Refunds are not issued for errors in the ad content or scheduling that are the fault of the advertiser.</li>
        </ul>
      </section>

      <section>
        <h5>Contact Us</h5>
        <p>For any questions or concerns regarding our refund policy, please contact our support team at support@mediadeal.ng.
          By using Media Deal, you agree to this refund policy. We reserve the right to modify this policy at any time. Changes will be posted on our website and communicated to our users.</p>
      </section>
    </div>
  </div>
</div>

@include('home.footer')